---
- name: get destion list
  hosts: localhost
  connection: local
  vars: 
    orgid: "{{ organizationId }}"
    base_url: "https://management.api.umbrella.com/v1"
  tasks:
    - name: get destination list in Umbrella
      uri: 
        url: "{{ base_url }}/organizations/{{ orgid }}/destinationlists?limit=1"
        method: GET
        status_code: 200
        url_username: "{{ key }}"
        url_password: "{{ secret }}"
        headers:
          Content-Type: "application/json"
          Accept: application/json
      register: destination

    - name: print results to console
      debug:
        msg: "{{ destination }}"


