---
- name: onboard a New LTM
  hosts: all
  connection: local
  tasks:
    - name: parse vs
      set_fact:
        node_list: "{{ virtual_servers | return_list }}"
      
    - name: configure nodes
      loop: "{{ node_list }}"
      bigip_node:
        name: "{{ item.name }}"
        address: "{{ item.ip_addr }}"
        state: present
        provider: "{{ conn_params }}"

    - name: Configure pool
      loop: "{{ virtual_servers }}" 
      bigip_pool:
        name: "pool_{{ item.pool_name }}"
        provider: "{{ conn_params }}"
        state: present
        lb_method: "{{ item.pool_lb_method }}"


    - name: Configure virtual server
      loop: "{{ virtual_servers }}"
      bigip_virtual_server:
        name: "{{ item.vs_name }}"
        destination: "{{ item.ip_addr }}"
        port: "{{ item.port }}"
        pool: "pool_{{ item.pool_name }}"
        description: Web App
        profiles: "{{ item.profiles }}"
        state: present

