---

- tasks:
    - name: Collect BIG-IP information for gtm
      bigip_device_info:
        gather_subset:
          - ltm-pools
          - interfaces
        provider:
          server: 10.82.10.32
          user: admin
          password: 1qaz@WSX
      delegate_to: localhost

    - name: License BIG-IP using a key
      bigip_device_license:
        state: present
        accept_eula: true
        license_key: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX"
        provider:
          server: "lb.mydomain.com"
          validate_certs: false
          user: "admin"
          password: "secret"
      delegate_to: localhost

# this example demo enabling ssh and setting all ips and adding a banner
    - name: Set the banner for the SSHD service from a file
      bigip_device_sshd:
        login: enabled
        allow:
          - all
          # - 172.27.1.10
          # - 172.27.*.*
          # - 172.27.0.0/255.255.0.0
        banner: enabled
        banner_text: "{{ lookup('file', '/path/to/file') }}"
        provider:
          password: secret
          server: lb.mydomain.com
          user: admin
      delegate_to: localhost

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        save: yes
        provider:
          server: lb.mydomain.com
          password: secret
          user: admin
      delegate_to: localhost

    - name: Reset the BIG-IP configuration, for example, to RMA the device
      bigip_config:
        reset: yes
        save: yes
        provider:
          server: lb.mydomain.com
          password: secret
          user: admin
      delegate_to: localhost
